### ISSUE TITLE
it seen that something happen when I import the package......

### ISSUE THREAD

**Issue by alphaDeng** [jaabell/gmsh2opensees#1]
when I import gmsh2opensees, python will raise the error：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/deng/gmsh2opensees-main/gmsh2opensees/__init__.py", line 18, in <module>
    from gmsh2opensees.g2o_utils import *
  File "/home/deng/gmsh2opensees-main/gmsh2opensees/g2o_utils.py", line 12, in <module>
    import opensees as ops
ModuleNotFoundError: No module named 'opensees'

the python is working in linux，the opensees package is openseespy. maybe I should choose openseesRT?

**Comment by jaabell** [comment]
This particular line might be different depending on how you installed
openseespy. I currently compile my own openseespy and don't use the repo
version, which is why its different from me. Feel free to change it to what
works best for you. If you let me know, then I can probably create a
version of the code that automatically chooses the right one depending on
configuration.

**Comment by antonsurv** [comment]
I change all in gmsh2opensees/g2o_elements_functions.py, gmsh2opensees/g2o_nodes_functions.py, gmsh2opensees/g2o_utils.py, gmsh2opensees/g2o_viz.py and rerun setup.py 

```
if os.name == 'nt':
	import openseespy.opensees as ops
else:   #not checked in mac
	import opensees as ops
```

into:
```
if os.name == 'nt':
	import openseespy.opensees as ops
else:   #not checked in mac
	import openseespy.opensees as ops
```

and it worked for me :)

**Comment by jaabell** [comment]
Thanks. Are you on a mac?
There should be a os.name = "darwin" for mac.


--

José A. Abell, PhD
Ingeniero Civil
www.joseabell.com
